spring:
  application:
    name: infra-zuul

server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
   bff-test:
    path: /test/**
    serviceId: bff-test
    stringPrefix: true