spring:
  application:
    name: infra-config-server
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: file://${user.home}/kudos/workshop/config-repo/
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/